config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root to: "home#index"

  namespace :admin do
    get "", to: "home#index"
    resources :users, only: %i[index show destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    return unless user.has_role?(:admin)

    can :manage, :all
    can :read, :admin_homepage
    cannot :destroy, User, id: user.id
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource, polymorphic: true, optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/setting.rb
# frozen_string_literal: true

class Setting < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend FriendlyId

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :lockable
  acts_as_paranoid

  friendly_id :slug_candidates, use: %i[slugged finders]

  validates :name, presence: true, uniqueness: true

  after_update :notify_email_change, if: -> { saved_change_to_email? }

  def slug_candidates
    [:name, %i[name uid]]
  end

  def should_generate_new_friendly_id?
    saved_change_to_name? || super
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid)
      .first_or_create { |u| user_hash(u, auth) }
  end

  def self.user_hash(user, auth)
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user
  end

  private

    def notify_email_change
      UserMailer.email_modified_email(self, email_before_last_save, email_before_last_save).deliver_now
      UserMailer.email_modified_email(self, email_before_last_save, email).deliver_now
    end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < AdminController
    def index
      authorize! :read, :admin_homepage
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    load_and_authorize_resource

    def index
      @users = User.all
    end

    def show; end

    def destroy
      @user.errors[:base] << :is_current_user unless can?(:destroy, @user)
      @user.destroy
      flash[:notice] = t(:'flash.admin.users.destroy.success')
      redirect_to action: :index
    end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_user!
  layout "admin"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Add some fields to Devise account models
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Redirect if trying to access an unauthorized action
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_back(fallback_location: root_url)
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: account_params)
      devise_parameter_sanitizer.permit(:account_update, keys: account_params)
    end

    def account_params
      %i[name email password password_confirmation current_password]
    end
end

app/controllers/callbacks_controller.rb
# frozen_string_literal: true

class CallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %(
      def #{provider}
        @user = User.from_omniauth omniauth_auth
        sign_in_and_redirect @user
      end
    )
  end

  %i[twitter facebook].each do |provider|
    provides_callback_for provider
  end

  private

    def omniauth_auth
      request.env["omniauth.auth"]
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def alert_class(name)
    name = name.to_sym
    case name
    when :notice, :success then :success
    when :warning then :warning
    when :info then :info
    else :danger
    end
  end

  def empty_char
    safe_join [raw("&#8709;")]
  end

  def provider_profile_link(provider, uid)
    case provider
    when "twitter"
      link_to provider.capitalize, "https://twitter.com/intent/user?user_id=#{uid}"
    when "facebook"
      link_to provider.capitalize, "https://www.facebook.com/#{uid}"
    else
      empty_char
    end
  end

  def roles_list(roles)
    roles.any? ? roles.map(&:name).join(", ") : empty_char
  end

  def active_class(path)
    if path.is_a?(Array)
      "active" if path.map { |p| current_page?(p) }.include?(true)
    elsif current_page?(path)
      "active"
    end
  end
end

app/views/admin/home/index.html.haml
%h2= t :'.title'

%p= t :'.sub_title'

app/views/admin/users/index.html.haml
%h2= t :'.title'

%table.table
  %thead
    %tr
      %th #
      - %i( name email provider roles created_at ).each do |att|
        %th= User.human_attribute_name(att)
      %th= t :'scaffold.actions'
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= h user.name
        %td= h(user.email.nil? ? empty_char : user.email)
        %td= provider_profile_link user.provider, user.uid
        %td= roles_list(user.roles)
        %td= l user.created_at, format: :short
        %td
          - if can? :destroy, user
            = link_to t(:'scaffold.delete'), admin_user_path(user), method: :delete, class: 'btn btn-danger', data: { confirm: t(:'scaffold.confirm') }
          - else
            %button.btn.btn-danger{disabled: true, title: t(:'.cant_delete_yourself')}
              = t :'scaffold.delete'

app/views/admin/users/show.html.haml
%h2= t :'.title', name: @user.name

%h3= t :'.general'

.row
  .col-md-3
    %h4= User.human_attribute_name(:id)
    %p= @user.id
  .col-md-3
    %h4= User.human_attribute_name(:name)
    %p= h @user.name
  .col-md-3
    %h4= User.human_attribute_name(:email)
    %p=  h(@user.email.nil? ? empty_char : @user.email)
  .col-md-3
    %h4= User.human_attribute_name(:provider)
    %p= provider_profile_link @user.provider, @user.uid

%h3= User.human_attribute_name(:roles)

%p= roles_list @user.roles

%h3= t :'.activity'

.row
  .col-md-3
    %h4= User.human_attribute_name(:created_at)
    %p= l @user.created_at, format: :short
  .col-md-3
    %h4= User.human_attribute_name(:updated_at)
    %p= l @user.updated_at, format: :short
  .col-md-3
    %h4= User.human_attribute_name(:last_sign_in_at)
    %p= l @user.last_sign_in_at, format: :short
  .col-md-3
    %h4= User.human_attribute_name(:last_sign_in_ip)
    %p= link_to @user.last_sign_in_ip, "http://#{@user.last_sign_in_ip}"
.row
  .col-md-3
    %h4= User.human_attribute_name(:sign_in_count)
    %p= @user.sign_in_count
  .col-md-3
    %h4= User.human_attribute_name(:locked_at)
    %p= @user.locked_at.nil? ? '&empty;'.html_safe : l(@user.locked_at, format: :short)

%hr/

%p
  = link_to t(:'scaffold.back'), admin_users_path, class: 'btn btn-default'

app/views/home/index.html.haml
%h1= t :'.title'

app/views/layouts/_admin_navbar.html.haml
- resources = [{ model: User, right: :manage, path: admin_users_path }]

- can_see_admin_navbar = resources.map { |h| can?(h[:right], h[:model]) }.include?(true)

- if can_see_admin_navbar

  - paths = resources.map { |h| h[:path] }
  - paths << admin_path
  %li{class: "dropdown #{active_class paths}", role: 'presentation'}
    %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', href: '#', role: 'button'}
      = t(:'layouts.navbar.admin.name')
      %span.caret
    %ul.dropdown-menu
      %li{class: active_class(admin_path)}
        = link_to t(:'layouts.navbar.admin.home'), admin_path
      - resources.each do |resource|
        - if can? resource[:right], resource[:model]
          %li{class: active_class(resource[:path])}
            = link_to resource[:model].model_name.human.capitalize.pluralize, resource[:path]

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{alert_class name}"}
      %a.close{'data-dismiss' => 'alert'} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid

    .navbar-header
      %button.navbar-toggle.collapsed{'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'data-target' => '#navbar', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t(:'layouts.application_name'), root_path, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: active_class(root_path)}
          = link_to t(:'layouts.navbar.home'), root_path
        - if user_signed_in?
          = render 'layouts/admin_navbar'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          = render 'layouts/user_navbar'
          %li
            = link_to t(:'devise.sessions.destroy.sign_out'), destroy_user_session_path, method: :delete
        - else
          %li{class: active_class(new_session_path(User))}
            = link_to t(:'devise.sessions.new.sign_in'), new_session_path(User)
          %li{class: active_class(new_registration_path(User))}
            = link_to t(:'devise.registrations.new.sign_up'), new_registration_path(User)

app/views/layouts/_user_navbar.html.haml
- resources = [{ label: t(:'layouts.navbar.account.settings'), path: edit_user_registration_path }]

- paths = resources.map { |h| h[:path] }

%li{class: "dropdown #{active_class paths}", role: 'presentation'}
  %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', href: '#', role: 'button'}
    = h current_user.name
    %span.caret
  %ul.dropdown-menu
    - resources.each do |resource|
      %li{class: active_class(resource[:path])}
        = link_to resource[:label], resource[:path]

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}

    %title
      #{t(:'layouts.application_name')} - #{t(:'layouts.admin_panel_title')}

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    = favicon_link_tag 'favicon.png'

    = csrf_meta_tags

  %body

    .container
      = render 'layouts/header'
      = render 'layouts/alerts'

      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}
    %meta{content: 'Mon Petit Taille 3', name: 'description'}
    %meta{content: 'rhannequin', name: 'author'}

    %title= t :'layouts.application_name'

    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'

    :javascript
      // Get current locale from server
      var APP = window.APP = {}
      APP.locale = '#{I18n.locale}'

    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    = favicon_link_tag 'favicon.png'

  %body

    .container
      = render 'layouts/header'
      = render 'layouts/alerts'

      = yield